import { useState } from 'react';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { accountBalance, formatCurrency } from '../../src/domain/finance';
import { useLedgerStore } from '../../src/store/useLedgerStore';

export default function AccountsScreen() {
  const accounts = useLedgerStore((s) => s.accounts); const entries = useLedgerStore((s) => s.entries); const addAccount = useLedgerStore((s) => s.addAccount);
  const [adding, setAdding] = useState(false); const [name, setName] = useState(''); const [opening, setOpening] = useState('');
  const save = () => { const amount = Number(opening.replace(/,/g,'')); if (!name.trim() || !Number.isFinite(amount)) return; addAccount({ name:name.trim(), openingBalance:amount, currency:'INR' }); setName(''); setOpening(''); setAdding(false); };
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.container}><View style={styles.header}><View><Text style={styles.eyebrow}>ACCOUNTS</Text><Text style={styles.title}>Where your money lives.</Text></View><Pressable style={styles.add} onPress={()=>setAdding(!adding)}><Text style={styles.addText}>＋</Text></Pressable></View>
    {accounts.map(a=><View key={a.id} style={styles.card}><View><Text style={styles.name}>{a.name}</Text><Text style={styles.muted}>INR · local account</Text></View><Text style={styles.balance}>{formatCurrency(accountBalance(a,entries))}</Text></View>)}
    {adding && <View style={styles.form}><Text style={styles.section}>New account</Text><TextInput style={styles.input} placeholder="Account name" value={name} onChangeText={setName}/><TextInput style={styles.input} placeholder="Opening balance" keyboardType="decimal-pad" value={opening} onChangeText={setOpening}/><Pressable style={styles.button} onPress={save}><Text style={styles.buttonText}>Add account</Text></Pressable></View>}
    <View style={styles.note}><Text style={styles.noteTitle}>Privacy by design</Text><Text style={styles.noteText}>PocketLedger keeps your ledger on-device. No bank connection is required for the core experience.</Text></View>
  </ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F7F7F2'},container:{padding:22,gap:14},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',paddingTop:10,marginBottom:6},eyebrow:{fontSize:12,fontWeight:'800',letterSpacing:2,opacity:.5},title:{fontSize:28,fontWeight:'800',lineHeight:34,maxWidth:290},add:{width:46,height:46,borderRadius:23,backgroundColor:'#17251B',alignItems:'center',justifyContent:'center'},addText:{color:'#fff',fontSize:26},card:{backgroundColor:'#fff',borderRadius:20,padding:18,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},name:{fontSize:16,fontWeight:'800',marginBottom:5},muted:{fontSize:12,color:'#6F746F'},balance:{fontSize:17,fontWeight:'800'},form:{backgroundColor:'#fff',borderRadius:20,padding:18,gap:11},section:{fontSize:18,fontWeight:'800'},input:{borderWidth:1,borderColor:'#E1E2DE',borderRadius:13,padding:13,fontSize:15},button:{backgroundColor:'#17251B',borderRadius:13,padding:14,alignItems:'center'},buttonText:{color:'#fff',fontWeight:'800'},note:{backgroundColor:'#E8EEE9',borderRadius:20,padding:18,gap:7,marginTop:4},noteTitle:{fontSize:16,fontWeight:'800'},noteText:{lineHeight:20,color:'#3E4941'}});